### ISSUE TITLE
Fix Transcriptome Assembly Workflow or Build new Pipeline? 

### ISSUE THREAD

**Issue by aleighbrown** [frattalab/rna_seq_snakemake#21]
Is adding transcriptome assmebly correct for this pipeline?

Basically we need to change how we compare the novel transcripts to the assembled trnascripts,e.g. the tool we're using compares intron chains, which when we compare against the reference transcriptome, throws out novel extension exons. 

The other thing it may be work rebasing to use the rna-bridge + stringtie's approach of "super-reads" which makes me think it's maybe a better choice to  remove the scallop + stringtie calls entirely from here, and rebuild a new pipeline exclusively for transcriptome assembly

which would include

1. rna-bridge
2. super-reads
3. assembly using both
4. comparison of the new things to the annotated trancripts

**Comment by SamBryce-Smith** [comment]
So I don't forget our discussions, I think we're deciding on 2 separate workflows/repos. 

For this repo, a simpler workflow of:

1. Run StringTie2, add novel transcripts to reference txome for quantification with Salmon

And a separate pipeline exclusively for txome assembly, using every tool we can to find all novel transcripts we can

**Comment by aleighbrown** [comment]
Closing this as we've decided this should be a separate pipeline entirely
