### ISSUE TITLE
Update reference_files_species table to update human to GENCODE v 42

### ISSUE THREAD

**Issue by aleighbrown** [frattalab/rna_seq_snakemake#47]

**Comment by SamBryce-Smith** [comment]
- Ignore te_gtf for now (put in a dummy value)
- Use https://github.com/frattalab/rna_seq_single_steps/blob/main/single_steps/gtf_to_bed12.smk to generate BED12 from GTF file
- Use GFFread to make the transcriptome FASTA - https://github.com/gpertea/gffread - Anna-Leigh has it installed in her tools directory on the cluster
