### ISSUE TITLE
Fix MultiQC rule and add to workflows

### ISSUE THREAD

**Issue by SamBryce-Smith** [frattalab/rna_seq_snakemake#5]
see title... Would be good to get this working for both FASTQC and mapping reports...

**Comment by aleighbrown** [comment]
There's a script in rules that will read the star output logs and spit out the mapping info

```
Rscript rna_seq_snakemake/scripts/parse_star_output.R --STAR /SAN/vyplab/alb_projects/data/buratti_new_shsy5y/STAR_aligned/ --out  /SAN/vyplab/alb_projects/data/buratti_new_shsy5y/mapping_stats.csv
```


sample | uniquely_mapped | mapped_to_multiple_loci | mapped_to_too_many_loci | unmapped_reads | number_of_input_reads
-- | -- | -- | -- | -- | --
CTR01 | 60645005 | 1829254 | 12068 | 1038781 | 63525108
CTR02 | 60292900 | 2404579 | 12831 | 1072210 | 63782520
CTR03 | 60428314 | 2165052 | 12648 | 1175369 | 63781383
CTR07 | 68914577 | 2870382 | 21778 | 772550 | 72579287
CTR08 | 61890202 | 2055708 | 16591 | 697936 | 64660437
CTR09 | 56711797 | 2592883 | 17651 | 735593 | 60057924
TDP04 | 63777957 | 2644236 | 15462 | 1764677 | 68202332
TDP05 | 59601540 | 2189325 | 14657 | 1544785 | 63350307
TDP06 | 67589766 | 2556140 | 14505 | 1661381 | 71821792



But I haven't hooked it into any rules yet

**Comment by aleighbrown** [comment]
Also another one that sort of parses the fastp output

python3 rna_seq_snakemake/scripts/parse_fastp_json.py -i /SAN/vyplab/alb_projects/data/buratti_new_shsy5y/fastp_trimmed/fastqs_TDP06_fastp.json -o wtf.csv


  | total_reads | total_bases | q20_bases | q30_bases | q20_rate | q30_rate | read1_mean_length | read2_mean_length | gc_content | insert_size_peak | sample_name
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
before_filtering | 143676550 | 2.1551E+10 | 2.124E+10 | 2.0603E+10 | 0.985537 | 0.955994 | 150 | 150 | 0.471036 | 247 | TDP06
after_filtering | 143643584 | 2.1422E+10 | 2.1122E+10 | 2.0494E+10 | 0.985984 | 0.956659 | 149 | 149 | 0.47064 | 247 | TDP06
